# Generated by Django 3.1.3 on 2020-11-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201129_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
    ]
