# Generated by Django 3.1.3 on 2020-11-29 10:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projects_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
