# Generated by Django 3.1.3 on 2020-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
