# Generated by Django 3.1.3 on 2020-11-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectsapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsapi',
            old_name='tile',
            new_name='title',
        ),
    ]
