# Generated by Django 3.1.3 on 2020-12-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201130_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='ratings',
        ),
    ]
